name: basictest

on:
  workflow_dispatch:
 
defaults:
  run:
    shell: bash

jobs:
  build-erofs-utils:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build erofs-utils
        run: |
          sudo modprobe squashfs
          sudo modprobe erofs
        timeout-minutes: 10
